# Generated by Django 5.1.3 on 2025-02-23 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0003_remove_users_password_hash_users_groups_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users",
            old_name="dob",
            new_name="date_of_hire",
        ),
    ]
