# Generated by Django 5.1.3 on 2025-01-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_remove_users_password_hash_users_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('qa', 'QA'), ('staff', 'Staff')], default='staff', max_length=20),
        ),
    ]
