# Generated by Django 5.1.3 on 2025-03-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_rename_dob_users_date_of_hire'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Light Mode'), ('dark', 'Dark Mode')], default='light', max_length=10),
        ),
    ]
