# Generated by Django 5.1.3 on 2025-01-23 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardsettings',
            name='user',
        ),
        migrations.DeleteModel(
            name='AdminDashboardActivity',
        ),
        migrations.DeleteModel(
            name='DashboardSettings',
        ),
    ]
