# Generated by Django 5.1.3 on 2025-02-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_inventorypicklist_unique_order_picklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorypicklist',
            name='picklist_complete_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
