# Generated by Django 5.1.3 on 2025-02-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_inventorypicklist_picklist_complete_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorypicklistitem',
            name='item_picked_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
