# Generated by Django 5.1.3 on 2025-02-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0012_inventorypicklistitem_item_picked_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorypicklistitem",
            name="picked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
