# Generated by Django 5.1.3 on 2025-03-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_inventorypicklistitem_picked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorypicklist',
            name='warehouse_nb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventorypicklistitem',
            name='area',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventorypicklistitem',
            name='lineup_nb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventorypicklistitem',
            name='material_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventorypicklistitem',
            name='model_nb',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
