# Generated by Django 5.1.3 on 2025-04-03 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_inventorypicklist_warehouse_nb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorypicklistitem',
            name='manually_picked',
            field=models.BooleanField(default=False),
        ),
    ]
