# Generated by Django 5.1.3 on 2025-04-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_inventorypicklistitem_repick_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorypicklistitem',
            name='actual_picked_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
