# Generated by Django 5.1.3 on 2025-01-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderpart_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='start_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
