# Generated by Django 5.1.3 on 2025-02-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orders_start_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(default='Not Started', max_length=255, null=True),
        ),
    ]
