# Generated by Django 5.1.3 on 2025-03-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpart',
            name='packed_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='pack_complete_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='ship_complete_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
