# Generated by Django 5.1.3 on 2025-03-23 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderpart_packed_timestamp_and_more'),
        ('orders', '0007_orders_customer_name_orders_end_timestamp_and_more'),
    ]

    operations = [
    ]
