# Generated by Django 5.1.3 on 2025-03-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orders_customer_name_orders_end_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpart',
            name='area',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderpart',
            name='department',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderpart',
            name='final_model',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderpart',
            name='importance',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderpart',
            name='lineup_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderpart',
            name='lineup_nb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderpart',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderpart',
            name='material_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
