# Generated by Django 5.1.3 on 2025-03-24 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderpart_area_orderpart_department_and_more'),
        ('orders', '0009_remove_orders_pack_complete_timestamp_and_more'),
    ]

    operations = [
    ]
