# Use an official Python runtime
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy requirements
COPY requirements.txt /app/

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire backend code
COPY . /app

# Expose port 8000 
EXPOSE 8000

# Set the default command 
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
