# Generated by Django 5.1.3 on 2025-01-14 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturingLists', '0004_remove_manufacturinglistitem_sku_and_more'),
        ('parts', '0008_alter_part_sku_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturingTask',
            fields=[
                ('manufacturing_task_id', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('cutting', 'cutting'), ('bending', 'bending'), ('painting', 'painting'), ('completed', 'completed'), ('cutting QA', 'cuttingQA'), ('bending QA', 'bendingQA'), ('painting QA', 'paintingQA')], max_length=25)),
                ('cut_start_time', models.DateField(null=True)),
                ('cut_end_time', models.DateField(null=True)),
                ('bend_start_time', models.DateField(null=True)),
                ('bend_end_time', models.DateField(null=True)),
                ('paint_start_time', models.DateField(null=True)),
                ('paint_end_time', models.DateField(null=True)),
                ('cut_qa', models.BooleanField(default=False)),
                ('bend_qa', models.BooleanField(default=False)),
                ('paint_qa', models.BooleanField(default=False)),
                ('bend_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bend_employee', related_query_name='bend_employee', to=settings.AUTH_USER_MODEL)),
                ('bend_qa_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bend_qa_employee', related_query_name='bend_qa_employee', to=settings.AUTH_USER_MODEL)),
                ('cut_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cut_employee', related_query_name='cut_employee', to=settings.AUTH_USER_MODEL)),
                ('cut_qa_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cut_qa_employee', related_query_name='cut_qa_employee', to=settings.AUTH_USER_MODEL)),
                ('paint_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paint_employee', related_query_name='paint_employee', to=settings.AUTH_USER_MODEL)),
                ('paint_qa_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paint_qa_employee', related_query_name='paint_qa_employee', to=settings.AUTH_USER_MODEL)),
                ('sku_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.part')),
            ],
        ),
    ]
