# Generated by Django 5.1.3 on 2025-01-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturingLists', '0006_manufacturinglistitem_manufacturing_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturingtask',
            name='bend_end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='manufacturingtask',
            name='bend_start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='manufacturingtask',
            name='cut_end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='manufacturingtask',
            name='cut_start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='manufacturingtask',
            name='paint_end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='manufacturingtask',
            name='paint_start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
