# Generated by Django 5.1.3 on 2025-01-17 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturingLists', '0007_alter_manufacturingtask_bend_end_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturingtask',
            old_name='bend_employee',
            new_name='bending_employee',
        ),
        migrations.RenameField(
            model_name='manufacturingtask',
            old_name='bend_end_time',
            new_name='bending_end_time',
        ),
        migrations.RenameField(
            model_name='manufacturingtask',
            old_name='bend_start_time',
            new_name='bending_start_time',
        ),
        migrations.RenameField(
            model_name='manufacturingtask',
            old_name='bend_qa_employee',
            new_name='cutting_employee',
        ),
        migrations.RenameField(
            model_name='manufacturingtask',
            old_name='cut_end_time',
            new_name='cutting_end_time',
        ),
        migrations.RenameField(
            model_name='manufacturingtask',
            old_name='cut_start_time',
            new_name='cutting_start_time',
        ),
        migrations.RenameField(
            model_name='manufacturingtask',
            old_name='cut_employee',
            new_name='nesting_employee',
        ),
        migrations.RenameField(
            model_name='manufacturingtask',
            old_name='bend_qa',
            new_name='prod_qa',
        ),
        migrations.RenameField(
            model_name='manufacturingtask',
            old_name='cut_qa_employee',
            new_name='prod_qa_employee',
        ),
        migrations.RemoveField(
            model_name='manufacturingtask',
            name='cut_qa',
        ),
        migrations.AddField(
            model_name='manufacturingtask',
            name='nesting_end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='manufacturingtask',
            name='nesting_start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='manufacturingtask',
            name='welding_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weld_employee', related_query_name='weld_employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manufacturingtask',
            name='welding_end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='manufacturingtask',
            name='welding_start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='manufacturinglistitem',
            name='manufacturing_process',
            field=models.CharField(choices=[('nesting', 'nesting'), ('bending', 'bending'), ('cutting', 'cutting'), ('welding', 'welding'), ('painting', 'painting'), ('completed', 'completed'), ('production QA', 'production QA'), ('painting QA', 'painting QA')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturinglistitem',
            name='process_progress',
            field=models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturingtask',
            name='status',
            field=models.CharField(choices=[('nesting', 'nesting'), ('bending', 'bending'), ('cutting', 'cutting'), ('welding', 'welding'), ('painting', 'painting'), ('production_qa', 'production_qa'), ('painting_qa', 'painting_qa'), ('completed', 'completed')], max_length=25),
        ),
    ]
