# Generated by Django 5.1.3 on 2025-01-21 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturingLists', '0007_alter_manufacturingtask_bend_end_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturingtask',
            name='bend_employee',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bend_employee', related_query_name='bend_employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='manufacturingtask',
            name='bend_end_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturingtask',
            name='bend_qa_employee',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bend_qa_employee', related_query_name='bend_qa_employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='manufacturingtask',
            name='bend_start_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturingtask',
            name='cut_employee',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cut_employee', related_query_name='cut_employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='manufacturingtask',
            name='cut_end_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturingtask',
            name='cut_qa_employee',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cut_qa_employee', related_query_name='cut_qa_employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='manufacturingtask',
            name='cut_start_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturingtask',
            name='paint_employee',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paint_employee', related_query_name='paint_employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='manufacturingtask',
            name='paint_end_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturingtask',
            name='paint_qa_employee',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paint_qa_employee', related_query_name='paint_qa_employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='manufacturingtask',
            name='paint_start_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
