# Generated by Django 5.1.3 on 2025-03-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OAReport',
            fields=[
                ('oa_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('location', models.CharField(max_length=255, null=True)),
                ('sku_color', models.CharField(max_length=255)),
                ('material_type', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('lineup_nb', models.CharField(max_length=255)),
                ('lineup_name', models.CharField(max_length=255)),
                ('due_date', models.DateTimeField(null=True)),
                ('client_name', models.CharField(max_length=255)),
                ('project_type', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('final_model', models.CharField(max_length=255)),
            ],
        ),
    ]
