# Generated by Django 5.1.3 on 2025-03-21 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oa_input', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='oareport',
            unique_together={('order_id', 'sku_color', 'qty', 'lineup_nb', 'due_date', 'project_type', 'area', 'final_model')},
        ),
    ]
